name: covid19
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - pip
  - bokeh
  - numpy=1.18.4
  - pygments=2.6.1
  - pandas
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - readline=8.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.3.1
  - six=1.14.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.2
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - click==7.1.2
    - fancycompleter==0.9.1
    - flask==1.1.2
    - itsdangerous==1.1.0
    - pdbpp==0.10.2
    - pyrepl==0.9.0
    - werkzeug==1.0.1
    - wget==3.2
    - wmctrl==0.3

